# Site settings
title: Junio Summerjobs
email: suport@junio.ro
description: > # this means to ignore newlines until "baseurl:"
  Summer job = job de vară. Este un mod în care poți câștiga niște bani și acumula un pic de experiență în loc să procrastinezi timp de trei luni.
descriptionHTML: >
  Summer job = job de vară. Este un mod în care poți câștiga niște bani și acumula un pic de experiență în loc <del>să freci menta</del> <del>să tragi mâța de coadă</del> <em>să procrastinezi</em> timp de trei luni.
baseurl: ''
static: '/static'
url: 'http://summer.junio.ro'
# twitter_username: jekyllrb
# github_username:  jekyll


# Build settings
safe: false
excerpt_separator: <!--/excerpt-->
gems:
  - jekyll-sitemap
markdown: kramdown
exclude:
  - 'package.json'
  - 'Gruntfile.js'
  - 'grunt/'
  - 'node_modules/'
  - 'src/'
  - '*.ai'
  - '.DS_Store'
  - '._DS_Store'
  - '.git/'
  - '.gitignore'
  - 'template-company/'
  - 'anritsu-solutions/'
